const router = require('express').Router()
const seeds =require('../Config/seeds')
const user = require('../apis/user1/user1Controller')
const parkingcontroller = require('../apis/addparking/parkingcontroller')
const citycontroller = require('../apis/addcity/citycontroller')
const slotcontroller = require('../apis/slotdetail/slotcontroller')
const ordercontroller = require('../apis/ordercheck/ordercontroller')
router.get('/',function(req,res){
    res.send("You are in admin Router")
})
router.post('/login',user.login)

router.post('/deleteparking',parkingcontroller.deleteparking)
router.post('/addparking',parkingcontroller.addparking)
router.post('/showparking',parkingcontroller.showparking)
router.post('/updateparking',parkingcontroller.updateparking)
router.post('/deletecity',citycontroller.deletecity)
router.post('/addcity',citycontroller.addcity)
router.post('/showcity',citycontroller.showcity)
router.post('/updatecity',citycontroller.updatecity)
router.post('/selectslot',slotcontroller.selectslot)
router.post('/showslot',slotcontroller.showslot)
router.post('/updateslot',slotcontroller.updateslot)
router.post('/deleteslot',slotcontroller.deleteslot)
router.post('/getall',ordercontroller.getall)
router.post('/getsingle',ordercontroller.getsingle)
router.use(require('../apis/admin/adminmiddleware'))
router.post('/insertuser',seeds.insertuser)

module.exports = router;